create table category (id int8 generated by default as identity, name varchar(255) not null, primary key (id));
create table show (id int8 generated by default as identity, name varchar(255), primary key (id));
create table show_categories (id_show int8 not null, id_category int8 not null);
alter table if exists show_categories add constraint FK7vjhvrob183unvba3r6w7igee foreign key (id_category) references category;
alter table if exists show_categories add constraint FKebbgwq8vbs48vnkniaxf9no7j foreign key (id_show) references show;
